#!/usr/bin/env bash
# =============================================================================
# setup-server.sh — Idempotent Typesense setup for Incenva Rebate Finder
#
# Installs Typesense 26.0 via the official APT repository, configures the
# server, and starts the systemd service.
#
# Usage:
#   sudo bash scripts/typesense/setup-server.sh
#
# Override defaults via environment variables before running:
#   TYPESENSE_API_KEY=my-secret-key sudo bash ...
#
# Safe to run multiple times — every step checks if work is already done.
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ── Color helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "\n${BLUE}[setup]${NC} ${BOLD}$*${NC}"; }
ok()   { echo -e "  ${GREEN}✔${NC}  $*"; }
skip() { echo -e "  ${YELLOW}─${NC}  $* (already done)"; }
warn() { echo -e "  ${YELLOW}⚠${NC}  $*"; }
fail() { echo -e "\n${RED}[error]${NC} $*\n"; exit 1; }
hr()   { echo -e "${BLUE}────────────────────────────────────────────────────${NC}"; }

# ── Root guard ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || fail "Run as root: sudo bash $0"

# ── Config ────────────────────────────────────────────────────────────────────
TYPESENSE_VERSION="${TYPESENSE_VERSION:-26.0}"
TYPESENSE_DATA_DIR="${TYPESENSE_DATA_DIR:-/var/lib/typesense}"
TYPESENSE_CONFIG_DIR="${TYPESENSE_CONFIG_DIR:-/etc/typesense}"
TYPESENSE_CONFIG_FILE="$TYPESENSE_CONFIG_DIR/typesense-server.ini"
TYPESENSE_PORT="${TYPESENSE_PORT:-8108}"

# ── API key — use env var or generate a fresh random one ─────────────────────
if [[ -n "${TYPESENSE_API_KEY:-}" ]]; then
  _API_KEY="$TYPESENSE_API_KEY"
  _KEY_SOURCE="from environment"
else
  _API_KEY="$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 32)"
  _KEY_SOURCE="auto-generated"
fi

hr
echo ""
echo -e "  ${BOLD}Typesense — Server Setup${NC}"
echo -e "  Version: ${BOLD}$TYPESENSE_VERSION${NC}"
echo -e "  Listen:  ${BOLD}localhost:$TYPESENSE_PORT${NC}"
echo ""
echo -e "  This script is idempotent — already-completed steps are skipped."
hr

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — APT prerequisites
# ─────────────────────────────────────────────────────────────────────────────
log "1/4  APT prerequisites"

MISSING_PKGS=()
for pkg in curl dpkg; do
  command -v "$pkg" &>/dev/null || MISSING_PKGS+=("$pkg")
done

if [[ ${#MISSING_PKGS[@]} -eq 0 ]]; then
  skip "Prerequisites already installed"
else
  apt-get update -qq
  apt-get install -y "${MISSING_PKGS[@]}" >/dev/null
  ok "Installed: ${MISSING_PKGS[*]}"
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — Install Typesense via direct .deb download
# The APT repo key endpoint is unreliable; the release .deb is stable.
# ─────────────────────────────────────────────────────────────────────────────
log "2/4  Typesense $TYPESENSE_VERSION"

if dpkg -s typesense &>/dev/null; then
  INSTALLED_VER="$(dpkg-query -W -f='${Version}' typesense 2>/dev/null || echo 'unknown')"
  skip "Typesense $INSTALLED_VER already installed"
else
  DEB_URL="https://dl.typesense.org/releases/${TYPESENSE_VERSION}/typesense-server-${TYPESENSE_VERSION}-amd64.deb"
  DEB_FILE="/tmp/typesense-server-${TYPESENSE_VERSION}-amd64.deb"

  curl -fsSL "$DEB_URL" -o "$DEB_FILE"
  apt-get install -y "$DEB_FILE" >/dev/null
  rm -f "$DEB_FILE"
  ok "Installed Typesense $TYPESENSE_VERSION"
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Data directory and config file
# ─────────────────────────────────────────────────────────────────────────────
log "3/4  Data directory and configuration"

# Ensure the typesense system user exists (the .deb normally creates it)
if ! id typesense &>/dev/null; then
  useradd --system --no-create-home --shell /usr/sbin/nologin typesense
  ok "Created system user 'typesense'"
else
  skip "System user 'typesense' already exists"
fi

# Data directory
if [[ -d "$TYPESENSE_DATA_DIR" ]]; then
  skip "Data directory $TYPESENSE_DATA_DIR"
else
  mkdir -p "$TYPESENSE_DATA_DIR"
  ok "Created $TYPESENSE_DATA_DIR"
fi
chown typesense:typesense "$TYPESENSE_DATA_DIR"
chmod 750 "$TYPESENSE_DATA_DIR"

# Config file — skip if it already exists to preserve operator edits
mkdir -p "$TYPESENSE_CONFIG_DIR"

if [[ -f "$TYPESENSE_CONFIG_FILE" ]]; then
  skip "Config file $TYPESENSE_CONFIG_FILE"
else
  cat > "$TYPESENSE_CONFIG_FILE" << EOF
; Typesense server configuration
; Generated by setup-server.sh — edit manually for production tuning.

[server]
data-dir   = $TYPESENSE_DATA_DIR
api-key    = $_API_KEY
listen-port= $TYPESENSE_PORT
enable-cors= true
EOF
  chown typesense:typesense "$TYPESENSE_CONFIG_FILE"
  chmod 640 "$TYPESENSE_CONFIG_FILE"
  ok "Written $TYPESENSE_CONFIG_FILE"
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — Enable and start the systemd service
# ─────────────────────────────────────────────────────────────────────────────
log "4/4  Systemd service"

systemctl enable typesense-server >/dev/null 2>&1
ok "Service enabled"

if systemctl is-active --quiet typesense-server; then
  skip "typesense-server already running"
else
  systemctl start typesense-server
  ok "Started typesense-server"
fi

# ─────────────────────────────────────────────────────────────────────────────
hr
echo ""
echo -e "  ${GREEN}${BOLD}Typesense setup complete!${NC}"
echo ""
echo -e "  Listen: ${BOLD}http://localhost:$TYPESENSE_PORT${NC}"
echo ""
echo -e "  ${YELLOW}${BOLD}TYPESENSE_API_KEY ($_KEY_SOURCE):${NC}"
echo -e "  ${BOLD}  $_API_KEY${NC}"
echo ""
echo -e "  Copy this key into your app .env:"
echo -e "    TYPESENSE_API_KEY=$_API_KEY"
echo ""
echo -e "  Useful commands:"
echo -e "    systemctl status typesense-server"
echo -e "    journalctl -u typesense-server -f"
echo -e "    curl http://localhost:$TYPESENSE_PORT/health"
hr
echo ""
