#!/usr/bin/env bash
# =============================================================================
# bootstrap.sh — First script to run on a blank Ubuntu 22.04 server
#
# Does everything needed BEFORE you can clone any private repo:
#   - Updates apt packages
#   - Installs git, curl, and other system tools
#   - Creates the rf system user
#   - Generates GitHub SSH deploy keys
#   - Writes ~/.ssh/config
#   - Clones this deployment repo
#   - Prints next steps
#
# Usage (run as root on a fresh Ubuntu 22.04 VPS):
#   curl -fsSL https://raw.githubusercontent.com/SomethingPressing/rebate-finder-deployement/main/scripts/bootstrap.sh | bash
#
#   OR after copying this file to the server manually:
#   sudo bash bootstrap.sh
#
# Safe to run multiple times — every step is idempotent.
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ── Color helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "\n${BLUE}[bootstrap]${NC} ${BOLD}$*${NC}"; }
ok()   { echo -e "  ${GREEN}✔${NC}  $*"; }
skip() { echo -e "  ${YELLOW}─${NC}  $* (already done)"; }
warn() { echo -e "  ${YELLOW}⚠${NC}  $*"; }
fail() { echo -e "\n${RED}[error]${NC} $*\n"; exit 1; }
hr()   { echo -e "${BLUE}────────────────────────────────────────────────────${NC}"; }

# ── Root guard ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || fail "Run as root: sudo bash $0"

# ── Config ────────────────────────────────────────────────────────────────────
APP_USER="${APP_USER:-rf}"
SSH_DIR="/home/$APP_USER/.ssh"
DEPLOY_REPO_URL="git@github-rebate-finder-deployement:SomethingPressing/rebate-finder-deployement.git"
DEPLOY_DIR="/home/$APP_USER/apps/deployment"

hr
echo ""
echo -e "  ${BOLD}Incenva Server Bootstrap${NC}"
echo "  Ubuntu $(lsb_release -rs 2>/dev/null || echo 'version unknown')"
echo "  App user: $APP_USER"
echo ""
hr

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — System packages
# ─────────────────────────────────────────────────────────────────────────────
log "1/6  System packages (git, curl, openssh-client, ufw)"

apt-get update -qq
apt-get install -y \
  git \
  curl \
  wget \
  unzip \
  openssh-client \
  ufw \
  ca-certificates \
  gnupg \
  lsb-release \
  software-properties-common \
  >/dev/null

ok "Packages installed"
ok "git $(git --version | awk '{print $3}')"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — System user
# ─────────────────────────────────────────────────────────────────────────────
log "2/6  System user '$APP_USER'"

if getent group "$APP_USER" &>/dev/null; then
  skip "Group '$APP_USER'"
else
  groupadd --system "$APP_USER"
  ok "Created group '$APP_USER'"
fi

if id "$APP_USER" &>/dev/null; then
  skip "User '$APP_USER'"
else
  useradd \
    --system \
    --gid "$APP_USER" \
    --shell /bin/bash \
    --home-dir "/home/$APP_USER" \
    --create-home \
    "$APP_USER"
  ok "Created user '$APP_USER'"
fi

mkdir -p "/home/$APP_USER/apps"
chown "$APP_USER:$APP_USER" "/home/$APP_USER/apps"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — .ssh directory
# ─────────────────────────────────────────────────────────────────────────────
log "3/6  SSH directory"

mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
chown "$APP_USER:$APP_USER" "$SSH_DIR"
ok "Directory $SSH_DIR (700)"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — Generate deploy keypairs
# ─────────────────────────────────────────────────────────────────────────────
log "4/6  GitHub deploy keypairs"

generate_key() {
  local name="$1"
  local label="$2"
  local key_file="$SSH_DIR/id_ed25519_${name}"

  if [[ -f "$key_file" ]]; then
    skip "Key: $label"
  else
    ssh-keygen -t ed25519 \
      -C "$APP_USER@$(hostname):$label" \
      -f "$key_file" \
      -N "" \
      >/dev/null 2>&1
    ok "Generated key: $label"
  fi

  chown "$APP_USER:$APP_USER" "$key_file" "${key_file}.pub"
  chmod 600 "$key_file"
  chmod 644 "${key_file}.pub"
}

generate_key "rebate_finder"             "rebate-finder"
generate_key "rebate_finder_scrapers"    "rebate-finder-scrapers"
generate_key "rebate_finder_deployement" "rebate-finder-deployement"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 5 — Write SSH config
# ─────────────────────────────────────────────────────────────────────────────
log "5/6  SSH config"

cat > "$SSH_DIR/config" << EOF
# Auto-generated by bootstrap.sh — do not edit manually
# Each host alias routes to github.com with the correct deploy key.

Host github-rebate-finder
    HostName github.com
    User git
    IdentityFile $SSH_DIR/id_ed25519_rebate_finder
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new

Host github-rebate-finder-scrapers
    HostName github.com
    User git
    IdentityFile $SSH_DIR/id_ed25519_rebate_finder_scrapers
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new

Host github-rebate-finder-deployement
    HostName github.com
    User git
    IdentityFile $SSH_DIR/id_ed25519_rebate_finder_deployement
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
EOF

chown "$APP_USER:$APP_USER" "$SSH_DIR/config"
chmod 600 "$SSH_DIR/config"
ok "Written $SSH_DIR/config"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 6 — Print public keys with GitHub instructions
# ─────────────────────────────────────────────────────────────────────────────
log "6/6  Public keys (add these to GitHub)"

declare -A REPOS=(
  ["rebate_finder"]="rebate-finder"
  ["rebate_finder_scrapers"]="rebate-finder-scrapers"
  ["rebate_finder_deployement"]="rebate-finder-deployement"
)

echo ""
hr
echo ""
echo -e "  ${BOLD}${GREEN}Bootstrap complete.${NC}"
echo ""
echo -e "  ${BOLD}Now add each public key to GitHub:${NC}"
echo -e "  1. Open the link shown for each repo"
echo -e "  2. Click  ${BOLD}Add deploy key${NC}"
echo -e "  3. Title: ${BOLD}rf@$(hostname)${NC}"
echo -e "  4. Paste the key shown below"
echo -e "  5. Leave 'Allow write access' unchecked → ${BOLD}Add key${NC}"
echo ""
hr

for key_suffix in rebate_finder rebate_finder_scrapers rebate_finder_deployement; do
  repo_name="${REPOS[$key_suffix]}"
  pub_key_file="$SSH_DIR/id_ed25519_${key_suffix}.pub"

  echo ""
  echo -e "  ${BOLD}▸ $repo_name${NC}"
  echo -e "  GitHub: ${BLUE}https://github.com/SomethingPressing/$repo_name/settings/keys${NC}"
  echo -e "  Key to paste:"
  echo ""
  echo "    $(cat "$pub_key_file")"
  echo ""
  hr
done

echo ""
echo -e "  ${YELLOW}${BOLD}Once all three keys are added on GitHub, run these in order:${NC}"
echo ""
echo -e "  ${BOLD}# 1. Verify GitHub connections${NC}"
echo -e "  sudo -u $APP_USER ssh -T github-rebate-finder"
echo -e "  sudo -u $APP_USER ssh -T github-rebate-finder-scrapers"
echo -e "  sudo -u $APP_USER ssh -T github-rebate-finder-deployement"
echo ""
echo -e "  ${BOLD}# 2. Clone this deployment repo${NC}"
echo -e "  sudo -u $APP_USER git clone \\"
echo -e "    $DEPLOY_REPO_URL \\"
echo -e "    $DEPLOY_DIR"
echo ""
echo -e "  ${BOLD}# 3. Run main app setup${NC}"
echo -e "  sudo bash $DEPLOY_DIR/scripts/rebate-finder/setup-server.sh"
echo ""
echo -e "  ${BOLD}# 4. Run scraper setup${NC}"
echo -e "  sudo bash $DEPLOY_DIR/scripts/scraper/setup-server.sh"
echo ""
echo -e "  ${BOLD}# 5. Load seed data${NC}"
echo -e "  bash $DEPLOY_DIR/scripts/rebate-finder/seed.sh"
echo ""
hr
echo ""
