#!/usr/bin/env bash
# =============================================================================
# setup-deploy-keys.sh — Generate GitHub SSH deploy keys for the rf user
#
# Creates one ed25519 key per repository, writes ~/.ssh/config so git uses
# the correct key for each repo, then prints the public keys you need to
# paste into GitHub → Repo Settings → Deploy keys.
#
# Usage (run as root on the server):
#   bash scripts/setup-deploy-keys.sh
#
# After this script finishes:
#   1. Add each printed public key to its GitHub repo (instructions printed)
#   2. Run:  bash scripts/verify-deploy-keys.sh
#   3. Then proceed with setup-server scripts
#
# Safe to run multiple times — skips keys that already exist.
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ── Color helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "\n${BLUE}[keys]${NC} ${BOLD}$*${NC}"; }
ok()   { echo -e "  ${GREEN}✔${NC}  $*"; }
skip() { echo -e "  ${YELLOW}─${NC}  $* (already exists)"; }
warn() { echo -e "  ${YELLOW}⚠${NC}  $*"; }
fail() { echo -e "\n${RED}[error]${NC} $*\n"; exit 1; }
hr()   { echo -e "${BLUE}────────────────────────────────────────────────────${NC}"; }
box()  { echo -e "${BOLD}$*${NC}"; }

# ── Root guard ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || fail "Run as root: sudo bash $0"

# ── Config ────────────────────────────────────────────────────────────────────
APP_USER="${APP_USER:-rf}"
SSH_DIR="/home/$APP_USER/.ssh"

declare -A REPOS=(
  [rebate_finder]="rebate-finder"
  [rebate_finder_scrapers]="rebate-finder-scrapers"
  [rebate_finder_deployement]="rebate-finder-deployement"
)

declare -A GITHUB_URLS=(
  [rebate_finder]="git@github.com:SomethingPressing/rebate-finder.git"
  [rebate_finder_scrapers]="git@github.com:SomethingPressing/rebate-finder-scrapers.git"
  [rebate_finder_deployement]="git@github.com:SomethingPressing/rebate-finder-deployement.git"
)

hr
echo ""
box "  Incenva — GitHub Deploy Key Setup"
echo "  User:   $APP_USER"
echo "  SSH dir: $SSH_DIR"
echo ""
hr

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — Create .ssh directory
# ─────────────────────────────────────────────────────────────────────────────
log "1/3  .ssh directory"

if id "$APP_USER" &>/dev/null; then
  ok "User '$APP_USER' exists"
else
  fail "User '$APP_USER' does not exist. Create it first:\n  adduser --disabled-password --gecos \"\" $APP_USER"
fi

mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
chown "$APP_USER:$APP_USER" "$SSH_DIR"
ok "Directory $SSH_DIR (700)"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — Generate keypairs
# ─────────────────────────────────────────────────────────────────────────────
log "2/3  Generate ed25519 keypairs"

for key in rebate_finder rebate_finder_scrapers rebate_finder_deployement; do
  repo_name="${REPOS[$key]}"
  key_file="$SSH_DIR/id_ed25519_${key}"

  if [[ -f "$key_file" ]]; then
    skip "Key for $repo_name ($key_file)"
  else
    ssh-keygen -t ed25519 \
      -C "$APP_USER@server:$repo_name" \
      -f "$key_file" \
      -N "" \
      >/dev/null 2>&1
    ok "Generated key for $repo_name"
  fi

  chown "$APP_USER:$APP_USER" "$key_file" "${key_file}.pub"
  chmod 600 "$key_file"
  chmod 644 "${key_file}.pub"
done

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Write SSH config
# ─────────────────────────────────────────────────────────────────────────────
log "3/3  SSH config ($SSH_DIR/config)"

cat > "$SSH_DIR/config" << EOF
# Auto-generated by setup-deploy-keys.sh
# Each host alias maps to a specific GitHub repo + key.

Host github-rebate-finder
    HostName github.com
    User git
    IdentityFile $SSH_DIR/id_ed25519_rebate_finder
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new

Host github-rebate-finder-scrapers
    HostName github.com
    User git
    IdentityFile $SSH_DIR/id_ed25519_rebate_finder_scrapers
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new

Host github-rebate-finder-deployement
    HostName github.com
    User git
    IdentityFile $SSH_DIR/id_ed25519_rebate_finder_deployement
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
EOF

chown "$APP_USER:$APP_USER" "$SSH_DIR/config"
chmod 600 "$SSH_DIR/config"
ok "Written $SSH_DIR/config"

# ─────────────────────────────────────────────────────────────────────────────
# PRINT: public keys + GitHub instructions
# ─────────────────────────────────────────────────────────────────────────────
echo ""
hr
echo ""
echo -e "  ${GREEN}${BOLD}Keys generated. Now add each public key to GitHub.${NC}"
echo ""
echo -e "  For each key below:"
echo -e "  1. Open the GitHub repo URL shown"
echo -e "  2. Go to  ${BOLD}Settings → Deploy keys → Add deploy key${NC}"
echo -e "  3. Title: ${BOLD}rf@$(hostname)${NC}"
echo -e "  4. Paste the key  (leave 'Allow write access' unchecked)"
echo -e "  5. Click  ${BOLD}Add key${NC}"
echo ""
hr

for key in rebate_finder rebate_finder_scrapers rebate_finder_deployement; do
  repo_name="${REPOS[$key]}"
  github_url="${GITHUB_URLS[$key]}"
  key_file="$SSH_DIR/id_ed25519_${key}.pub"
  # Convert SSH URL to HTTPS for the browser
  https_url="https://github.com/SomethingPressing/${repo_name}/settings/keys"

  echo ""
  echo -e "  ${BOLD}▸ ${repo_name}${NC}"
  echo -e "  GitHub URL: ${BLUE}${https_url}${NC}"
  echo -e "  Public key:"
  echo ""
  echo "    $(cat "$key_file")"
  echo ""
  hr
done

echo ""
echo -e "  ${YELLOW}After adding all three keys to GitHub, run:${NC}"
echo ""
echo -e "  ${BOLD}  bash scripts/verify-deploy-keys.sh${NC}"
echo ""
hr
echo ""
